### ISSUE TITLE
Jobs are not optional

### ISSUE THREAD

**Issue by worm-emoji** [lukemiles/api.lukemil.es#3]
Jobs should fail safely if API keys aren't present, making some endpoints optional/easier for people to deploy.

**Comment by denolfe** [comment]
The easiest way to do this would most likely be to check if the `config.section` exists.

For example: `if (!config.google) return;` before the job function in `sleep.js`

**Comment by worm-emoji** [comment]
@denolfe Good idea. I'm not near my dev machine for some time so if you want to put this in a PR I'd gladly accept it, otherwise I'll put up a commit eventually doing just this.

**Comment by worm-emoji** [comment]
@denolfe I actually saw that you implemented this in your fork. Perhaps I can change the repo name/readme to something less 'Luke-specific', we merge your commits, and I can add you as a contributor? Having additional help here would be great and encourage me to contribute more here myself. The more endpoints/functionality, the better.

**Comment by denolfe** [comment]
@lukemiles Most definitely! Implementing a personal API is something I've always wanted to build out. I have a bunch more integrations in mind as well.

**Comment by worm-emoji** [comment]
@denolfe Added you. How about you start a pull request?

**Comment by denolfe** [comment]
@lukemiles I'm actually not at my dev machine either. I'll probably be able to in a couple of hours, though.

EDIT: Oops, scratch that. I'll do one.
