### ISSUE TITLE
Weekly Plays are off for last.fm

### ISSUE THREAD

**Issue by denolfe** [lukemiles/api.lukemil.es#9]
I haven't familiarized myself with how you are getting the weekly plays yet. However, I did notice that the numbers are wildly high as of late.

**Comment by worm-emoji** [comment]
Yeah, this needs to be looked into. I've been crazy busy lately but I know
I haven't listened to thousands of song in the past week. Perhaps it has
something to do with the new last.fm redesign?

**Comment by denolfe** [comment]
That's a definite possibility, especially considering the notification at the top regarding how they're migrating data. Not a huge deal, just something I noticed.

**Comment by worm-emoji** [comment]
That's probably it. I'll look at the raw API data, but what the API seems to be returning doesn't reflect the website at all.
